// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1BBg3ux6n2lxKyV-DXJiHyIezGhxjubU',
    appId: '1:1078226748220:web:09ccb1b2c0d4b6fb835439',
    messagingSenderId: '1078226748220',
    projectId: 'naruto-be91a',
    authDomain: 'naruto-be91a.firebaseapp.com',
    storageBucket: 'naruto-be91a.firebasestorage.app',
    measurementId: 'G-JNQJEY0LN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtKN525zXVtg6fYEQ4SJoA7aI42i6NRr0',
    appId: '1:1078226748220:android:a06b1204303e14ea835439',
    messagingSenderId: '1078226748220',
    projectId: 'naruto-be91a',
    storageBucket: 'naruto-be91a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqI9UPsE9qVELxtBhR6ttVHcrruo-ZXPU',
    appId: '1:1078226748220:ios:bc1395dccfe12d56835439',
    messagingSenderId: '1078226748220',
    projectId: 'naruto-be91a',
    storageBucket: 'naruto-be91a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqI9UPsE9qVELxtBhR6ttVHcrruo-ZXPU',
    appId: '1:1078226748220:ios:bc1395dccfe12d56835439',
    messagingSenderId: '1078226748220',
    projectId: 'naruto-be91a',
    storageBucket: 'naruto-be91a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1BBg3ux6n2lxKyV-DXJiHyIezGhxjubU',
    appId: '1:1078226748220:web:35a300067e60d976835439',
    messagingSenderId: '1078226748220',
    projectId: 'naruto-be91a',
    authDomain: 'naruto-be91a.firebaseapp.com',
    storageBucket: 'naruto-be91a.firebasestorage.app',
    measurementId: 'G-HJC3YG1GB3',
  );
}
